### ISSUE TITLE
IOC application sometimes crashes sometime soon after iocInit

### ISSUE THREAD

**Issue by MarkRivers** [epics-modules/Dante#9]
The EPICS application sometimes crashes soon after iocInit, before I have attempted to change any PVs.

This is the stack trace.  It appears that all of the calls are in libXGL_DPP.so, not in the EPICS code.  It thus appears to be a problem in the vendor library, not in the EPICS driver.

```
(gdb) bt
#0  0x00007fcf66e69b65 in xgl_ctrl_brd_dpp_chain::wait_data(unsigned short, unsigned int, std::vector<unsigned int, std::allocator<unsigned int> >&) ()
   from /home/epics/devel/dante-1-0/lib/linux-x86_64/libXGL_DPP.so.1
#1  0x00007fcf66e63fe9 in xgl_ctrl_brd_dpp_chain::write(unsigned short, unsigned short, std::vector<unsigned int, std::allocator<unsigned int> >&, bool) ()
   from /home/epics/devel/dante-1-0/lib/linux-x86_64/libXGL_DPP.so.1
#2  0x00007fcf66e54cbf in xgl_ctrl_brd_dpp::config_DPP(unsigned short, unsigned int, bool, unsigned int) () from /home/epics/devel/dante-1-0/lib/linux-x86_64/libXGL_DPP.so.1
#3  0x00007fcf66e6369b in xgl_ctrl_brd_dpp_chain::config_DPP(unsigned short, unsigned short, unsigned int) () from /home/epics/devel/dante-1-0/lib/linux-x86_64/libXGL_DPP.so.1
#4  0x00007fcf66e60b31 in xgl_ctrl_brd_dpp_chain::configure(unsigned short, configuration) () from /home/epics/devel/dante-1-0/lib/linux-x86_64/libXGL_DPP.so.1
#5  0x00007fcf66e1c04e in std::_Function_handler<std::pair<unsigned short, std::vector<unsigned int, std::allocator<unsigned int> > > (), std::_Bind<std::pair<unsigned short, std::vector<unsigned int, std::allocator<unsigned int> > > (boards::*(std::shared_ptr<boards>, unsigned short, configuration))(unsigned short, configuration)> >::_M_invoke(std::_Any_data const&) () from /home/epics/devel/dante-1-0/lib/linux-x86_64/libXGL_DPP.so.1
#6  0x00007fcf66de5c8a in AsyncTask::operator()() const () from /home/epics/devel/dante-1-0/lib/linux-x86_64/libXGL_DPP.so.1
#7  0x00007fcf66e1be19 in std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::thread::_Invoker<std::tuple<AsyncTask> >, void> >::_M_invoke(std::_Any_data const&) ()
   from /home/epics/devel/dante-1-0/lib/linux-x86_64/libXGL_DPP.so.1
#8  0x00007fcf66dcc88b in std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) () from /home/epics/devel/dante-1-0/lib/linux-x86_64/libXGL_DPP.so.1
#9  0x00007fcf66371e70 in pthread_once () from /lib64/libpthread.so.0
#10 0x00007fcf66e1d20a in _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZNSt13__future_base17_Async_state_implINS1_IS2_IJ9AsyncTaskEEEEvEC4EOS7_EUlvE_EEEEE6_M_runEv ()
   from /home/epics/devel/dante-1-0/lib/linux-x86_64/libXGL_DPP.so.1
#11 0x00007fcf670ec0ef in execute_native_thread_routine () from /home/epics/devel/dante-1-0/lib/linux-x86_64/libXGL_DPP.so.1
#12 0x00007fcf6636ce25 in start_thread () from /lib64/libpthread.so.0
#13 0x00007fcf65225bad in clone () from /lib64/libc.so.6
```

**Comment by MarkRivers** [comment]
I observed a crash with a different stack trace, again all within libXGL_DPP.so
```
(gdb) bt
#0  0x00007ffff78525cd in std::_Rb_tree_insert_and_rebalance(bool, std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, std::_Rb_tree_node_base&) ()
   from /home/epics/devel/dante-1-0/lib/linux-x86_64/libXGL_DPP.so.1
#1  0x00007ffff75b4ed1 in std::pair<std::_Rb_tree_iterator<std::pair<unsigned int const, std::promise<std::vector<unsigned int, std::allocator<unsigned int> > > > >, bool> std::_Rb_tree<unsigned int, std::pair<unsigned int const, std::promise<std::vector<unsigned int, std::allocator<unsigned int> > > >, std::_Select1st<std::pair<unsigned int const, std::promise<std::vector<unsigned int, std::allocator<unsigned int> > > > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::promise<std::vector<unsigned int, std::allocator<unsigned int> > > > > >::_M_insert_unique<std::pair<unsigned char, std::promise<std::vector<unsigned int, std::allocator<unsigned int> > > > >(std::pair<unsigned char, std::promise<std::vector<unsigned int, std::allocator<unsigned int> > > >&&) () from /home/epics/devel/dante-1-0/lib/linux-x86_64/libXGL_DPP.so.1
#2  0x00007ffff7611404 in TCPIP_Port::write_cmd(unsigned short, unsigned short, std::vector<unsigned int, std::allocator<unsigned int> > const&) ()
   from /home/epics/devel/dante-1-0/lib/linux-x86_64/libXGL_DPP.so.1
#3  0x00007ffff7633fa7 in xgl_ctrl_brd_dpp_chain::write(unsigned short, unsigned short, std::vector<unsigned int, std::allocator<unsigned int> >&, bool) ()
   from /home/epics/devel/dante-1-0/lib/linux-x86_64/libXGL_DPP.so.1
#4  0x00007ffff7624b87 in xgl_ctrl_brd_dpp::config_DPP(unsigned short, unsigned int, bool, unsigned int) () from /home/epics/devel/dante-1-0/lib/linux-x86_64/libXGL_DPP.so.1
#5  0x00007ffff763369b in xgl_ctrl_brd_dpp_chain::config_DPP(unsigned short, unsigned short, unsigned int) () from /home/epics/devel/dante-1-0/lib/linux-x86_64/libXGL_DPP.so.1
#6  0x00007ffff76309fc in xgl_ctrl_brd_dpp_chain::configure(unsigned short, configuration) () from /home/epics/devel/dante-1-0/lib/linux-x86_64/libXGL_DPP.so.1
#7  0x00007ffff75ec04e in std::_Function_handler<std::pair<unsigned short, std::vector<unsigned int, std::allocator<unsigned int> > > (), std::_Bind<std::pair<unsigned short, std::vector<unsigned int, std::allocator<unsigned int> > > (boards::*(std::shared_ptr<boards>, unsigned short, configuration))(unsigned short, configuration)> >::_M_invoke(std::_Any_data const&) () from /home/epics/devel/dante-1-0/lib/linux-x86_64/libXGL_DPP.so.1
#8  0x00007ffff75b5c8a in AsyncTask::operator()() const () from /home/epics/devel/dante-1-0/lib/linux-x86_64/libXGL_DPP.so.1
#9  0x00007ffff75ebe19 in std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::thread::_Invoker<std::tuple<AsyncTask> >, void> >::_M_invoke(std::_Any_data const&) ()
   from /home/epics/devel/dante-1-0/lib/linux-x86_64/libXGL_DPP.so.1
#10 0x00007ffff759c88b in std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) () from /home/epics/devel/dante-1-0/lib/linux-x86_64/libXGL_DPP.so.1
#11 0x00007ffff6f0de70 in pthread_once () from /lib64/libpthread.so.0
#12 0x00007ffff75ed20a in _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZNSt13__future_base17_Async_state_implINS1_IS2_IJ9AsyncTaskEEEEvEC4EOS7_EUlvE_EEEEE6_M_runEv ()
   from /home/epics/devel/dante-1-0/lib/linux-x86_64/libXGL_DPP.so.1
#13 0x00007ffff78bc0ef in execute_native_thread_routine () from /home/epics/devel/dante-1-0/lib/linux-x86_64/libXGL_DPP.so.1
#14 0x00007ffff6f08e25 in start_thread () from /lib64/libpthread.so.0
#15 0x00007ffff5dc1bad in clone () from /lib64/libc.so.6
```

**Comment by MarkRivers** [comment]
I have found that the incidence of this crash appears to close to 100% of the time if I run the application under gdb.  This makes it very hard to debug other problems, but it does make it easy to reproduce this problem.

**Comment by MarkRivers** [comment]
I have not observed this problem since updating to the new library and the other suggested changes to the driver.
